// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDje9wRxv_sbSZN7DQdiWnttWnkWxfsqSs",
      authDomain: "poketinder-4e8de.firebaseapp.com",
      projectId: "poketinder-4e8de",
      storageBucket: "poketinder-4e8de.appspot.com",
      messagingSenderId: "520662777512",
      appId: "1:520662777512:web:d1da5c2d040d4cf8f94c9d");

  /*static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGyRVpT0zZGy2IW8WF1_RCoU40ZHd9Cr0',
    appId: '1:568789405540:web:4f09abf7966cccc95bb471',
    messagingSenderId: '568789405540',
    projectId: 'aulateste-fa172',
    authDomain: 'aulateste-fa172.firebaseapp.com',
    databaseURL: 'https://aulateste-fa172-default-rtdb.firebaseio.com',
    storageBucket: 'aulateste-fa172.appspot.com',
  );*/

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjFi8XuwDBB5ES0UWH1_l4GO0cDWDdKAE',
    appId: '1:325054520867:android:30948a2a00e07bf2a01b96',
    messagingSenderId: '325054520867',
    projectId: 'agendafirebase-fbcec',
    databaseURL: 'https://agendafirebase-fbcec.firebaseio.com',
    storageBucket: 'agendafirebase-fbcec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXHrv2Qd0ReyYQ8Ob2CvaqbzyOzaHd3jA',
    appId: '1:325054520867:ios:692b3b438dff2107a01b96',
    messagingSenderId: '325054520867',
    projectId: 'agendafirebase-fbcec',
    databaseURL: 'https://agendafirebase-fbcec.firebaseio.com',
    storageBucket: 'agendafirebase-fbcec.appspot.com',
    androidClientId:
        '325054520867-7usv097knp2kkftfk3jh4bhl688a8k8i.apps.googleusercontent.com',
    iosClientId:
        '325054520867-9pgerl3audej04ni6kaktnrbdkctdc6u.apps.googleusercontent.com',
    iosBundleId: 'com.example.agendaFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXHrv2Qd0ReyYQ8Ob2CvaqbzyOzaHd3jA',
    appId: '1:325054520867:ios:692b3b438dff2107a01b96',
    messagingSenderId: '325054520867',
    projectId: 'agendafirebase-fbcec',
    databaseURL: 'https://agendafirebase-fbcec.firebaseio.com',
    storageBucket: 'agendafirebase-fbcec.appspot.com',
    androidClientId:
        '325054520867-7usv097knp2kkftfk3jh4bhl688a8k8i.apps.googleusercontent.com',
    iosClientId:
        '325054520867-9pgerl3audej04ni6kaktnrbdkctdc6u.apps.googleusercontent.com',
    iosBundleId: 'com.example.agendaFirebase',
  );
}
